version: "3.9"
services:
  database:
    image: "postgres:14.1"
    restart: "no"
    environment:
      POSTGRES_DB: "cryptomarketdb"
      POSTGRES_USER: "farid"
      POSTGRES_PASSWORD: "crypto"
    ports:
      - "15432:5432"
